# Generated by Django 5.2.10 on 2026-02-01 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_remove_cartitem_unique_product_cart_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together=set(),
        ),
    ]
