# Generated by Django 5.2.10 on 2026-02-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_alter_cartitem_unique_together'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(['cart', 'product'], name='unique_product_cart'),
        ),
    ]
