# Generated by Django 5.2.10 on 2026-02-01 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_remove_cartitem_unique_product_cart_and_more'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_product_cart',
        ),
        migrations.AddConstraint(
            model_name='cartitem',
            constraint=models.UniqueConstraint(['cart', 'product'], name='unique_product_cart'),
        ),
    ]
