# Generated by Django 5.2.10 on 2026-02-01 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_remove_cartitem_unique_product_cart_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cartitem',
            name='unique_product_cart',
        ),
    ]
