# Generated by Django 5.2.10 on 2026-01-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('seller', 'Seller'), ('buyer', 'Buyer')], default='buyer', max_length=10),
        ),
    ]
